version=2.0.3
group=net.anvian.bedrockplus
java_version=25

# Common
minecraft_version=26.1
mod_name=Bedrock Plus Mod
mod_author=anvian
mod_id=bedrockplus
license=GPL-3.0
credits=PinhaColada2222
description=Adds a new variant of bedrock, which can be combined with netherite armor.
minecraft_version_range=[26.1, 26.3)
neo_form_version=26.1-1

# Fabric
fabric_version=0.144.0+26.1
fabric_loader_version=0.18.4

# NeoForge
neoforge_version=26.1.0.19-beta
neoforge_loader_version_range=[4,)

# anvian's lib
anvianslib_version=1.5.0

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
